import type { CSSProperties } from "react";
import type { LucideIcon as LucideIconComponent } from "lucide-react";
import {
  ArrowBigUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  BarChart3,
  Bed,
  Bell,
  BookOpen,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  CircleX,
  ClipboardList,
  Clock,
  Code,
  CodeXml,
  Construction,
  Crown,
  Database,
  Flame,
  Gamepad2,
  Gem,
  Grid2X2,
  GripVertical,
  HelpCircle,
  Home,
  LayoutDashboard,
  Lightbulb,
  Link,
  List,
  ListFilter,
  Lock,
  LockOpen,
  LogOut,
  MapPin,
  Medal,
  Menu,
  Minus,
  MoonStar,
  Package,
  PawPrint,
  Pencil,
  Play,
  PlayCircle,
  PlusCircle,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Route,
  Search,
  ShieldAlert,
  Sparkles,
  Star,
  SunMedium,
  Terminal,
  Trophy,
  Utensils,
  Users,
  UserSearch,
  Workflow,
  X,
  Zap,
} from "lucide-react";

const iconMap: Record<string, LucideIconComponent> = {
  add_circle: PlusCircle,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowBigUp,
  assignment: ClipboardList,
  auto_awesome: Sparkles,
  badge: BadgeCheck,
  bedtime: Bed,
  block: ShieldAlert,
  bolt: Zap,
  cancel: CircleX,
  chat: Bot,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_off: ShieldAlert,
  code: Code,
  code_blocks: CodeXml,
  construction: Construction,
  dashboard: LayoutDashboard,
  done: Check,
  done_all: CheckCircle2,
  drag_indicator: GripVertical,
  edit: Pencil,
  emoji_events: Trophy,
  emoji_objects: Lightbulb,
  error: CircleX,
  expand_more: ChevronDown,
  format_list_bulleted: List,
  forum: Bot,
  functions: Workflow,
  data_object: Database,
  dark_mode: MoonStar,
  grid_view: Grid2X2,
  groups: Users,
  help: HelpCircle,
  hourglass_top: Clock,
  hub: Link,
  insert_chart: BarChart3,
  inventory_2: Package,
  keyboard: Terminal,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  keyboard_double_arrow_up: ArrowBigUp,
  lightbulb: Lightbulb,
  light_mode: SunMedium,
  link: Link,
  local_fire_department: Flame,
  lock: Lock,
  lock_open: LockOpen,
  lock_person: Lock,
  logout: LogOut,
  menu: Menu,
  menu_book: BookOpen,
  military_tech: Medal,
  monetization_on: Gem,
  my_location: MapPin,
  notifications: Bell,
  pending: Clock,
  person: Home,
  person_search: UserSearch,
  pets: PawPrint,
  play_arrow: Play,
  play_circle: PlayCircle,
  play_lesson: PlayCircle,
  psychology: Bot,
  quiz: CircleHelp,
  refresh: RefreshCw,
  replay: Repeat2,
  remove: Minus,
  restart_alt: RotateCcw,
  restaurant: Utensils,
  rocket_launch: Zap,
  route: Route,
  schedule: Clock,
  search: Search,
  share: ArrowRight,
  show_chart: BarChart3,
  smart_toy: Bot,
  sports_esports: Gamepad2,
  star: Star,
  stars: Sparkles,
  terminal: Terminal,
  trending_up: ArrowBigUp,
  trending_down: ArrowDown,
  verified: BadgeCheck,
  view_module: Boxes,
  warning: ShieldAlert,
  workspace_premium: Crown,
  sort: ListFilter,
};

interface LucideIconProps {
  name: string;
  className?: string;
  style?: CSSProperties;
  strokeWidth?: number;
}

export default function LucideIcon({
  name,
  className,
  style,
  strokeWidth = 2.25,
}: LucideIconProps) {
  const Icon = iconMap[name] ?? CircleHelp;

  return (
    <Icon
      aria-hidden="true"
      className={className}
      focusable="false"
      size="1em"
      strokeWidth={strokeWidth}
      style={style}
    />
  );
}
